### ISSUE TITLE
May `lastupdated` be an ISO8601 timestamp?

### ISSUE THREAD

**Issue by emlun** [datasucker/netrunner-datasucker#4]
The README states:

> The `/status` endpoint returns a JSON object:
> - lastupdated (string => timestamp, milliseconds since the epoch)

Does "string => timestamp, milliseconds since the epoch" mean this field may either be a timestamp (presumably ISO8601 format) or an epoch milliseconds value, or are only milliseconds valid?

In case only milliseconds are permitted, what is the reasoning behind this? The way I see it, ISO8601 timestamps offer a few advantages (most notably being human-readable) while providing no less information. Thoughts on this?

**Comment by datasucker** [comment]
Good suggestion. I'll update the spec and change the Parse.com Datasucker appropriately.
