### ISSUE TITLE
Ordering of /sets

### ISSUE THREAD

**Issue by DoubleAitch** [datasucker/netrunner-datasucker#5]
The set.number objects do not 100% match the chronological ordering of the expansions due to being computed from the ordering of the setcode values in the source data (which are not in chronological order).

Specifically Upstalk (number:15, setid:333) should be after Honor & Profit (number:16, setid:342).

Adding a secondary sets.sort function based on the cyclenumber before assigning the set.number values should resolve the issue (~line 154 of main.js).

**Comment by datasucker** [comment]
Resolved. Good catch!
